name: Semantic-release
 
on:
  push: # main에 push할때 해당 workflow 실행
    branches: ["master"]
    
 
permissions:
  contents: read # for checkout
 
jobs:
  release:
    if: ${{ github.repository == 'ehdwn1991/muse_profile' && !github.event.repository.fork }}
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write        # to be able to publish a GitHub release
      issues: write          # to be able to comment on released issues
      pull-requests: write   # to be able to comment on released pull requests
      id-token: write        # to enable use of OIDC for npm provenance
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: "lts/*"
          registry-url: "https://npm.pkg.github.com/"
          scope: '@github-id'
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.ONLY_THIS_REPO_TOKEN }}
 